# Artificial Neural Network

### Importing the libraries

In [71]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [72]:
tf.__version__

'2.11.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [73]:
dataset=pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [74]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [75]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [76]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [77]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [78]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [79]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [80]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

### Feature Scaling

In [81]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [82]:
ann=tf.keras.models.Sequential() # initialising the artificial neural network (sequential model) in a sequence of layer(input layer,hidden layer,output layer)

### Adding the input layer and the first hidden layer

In [83]:
#adding a dense layer
# what is dense function below??
# dense() is an inbuilt function of Tensorflow library.
# dense Layer -> a dense layer is a layer that is deeply connected with its preceding layer which means the neurons of the layer are connected to every neuron of its preceding layer. This layer is the most commonly used layer in artificial neural network networks.
# The first Dense object is the first hidden layer. -->>> The input layer is specified as a parameter to the first Dense object's constructor.
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
#units is dimensionality of the output space(dimensionality of output space is number of neurons in that layer because each neuron will give one output). as here we take total 6 neurons in our layer each will give one output so dimensionality of output space of this hidden layer is 6 however we tried other dimensionality also but the output will be approx same for all so 6 is good for output space dimensionality
# as we discussed that the activation function for hidden layer is rectifier function so we give it as activation (relu is the code name for rectifier function)

### Adding the second hidden layer

In [84]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))


### Adding the output layer

In [85]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
# for binary output means for only two categories we'll use sigmoid activation function in output variable and for more than two categories we have to use softmax function ('softmax)
#as we all know output will be in form of 0/1 so only one output value is there <-> for which only one neuron is enough to give a output so dimensionality of output space in this output layer is 1 

## Part 3 - Training the ANN

### Compiling the ANN

In [86]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])#optimizer -> adam optimizer will update our weights according to the loss stochastic gradient descent
#loss -> A loss function is a function that compares the target and predicted output values <-> for binary data(in case of two categories-0/1) we'll use binary_crossentropy and for other categorical data(more than two categories) we'll use categorical_crossentropy 

### Training the ANN on the Training set

In [87]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)#because of batch learning(better method) we are giving parameter batch_size and classic default value for batch_size is 32 
# we can give any number of epochs as we wanted but not less because -> The epoch number is a critical hyperparameter for the algorithm. It specifies the number of epochs or full passes of the entire training dataset through the algorithm's training or learning process
#An epoch in a neural network is the training of the neural network with all the training data for one cycle

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6186 - accuracy: 0.6986
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4889 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4485 - accuracy: 0.7968
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4343 - accuracy: 0.8024
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4249 - accuracy: 0.8059
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4150 - accuracy: 0.8163
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4044 - accuracy: 0.8205
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3947 - accuracy: 0.8264
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3861 - accuracy: 0.8291
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3799 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

In [88]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)

1/1 [==============================] - 0s 73ms/step
[[False]]


### Predicting the Test set results

In [89]:
y_pred=ann.predict(x_test)#it will print the probabilities because of the sigmoid function we used in output layer
y_pred=y_pred>0.5

63/63 [==============================] - 0s 1ms/step


In [90]:
print(np.concatenate((y_test.reshape(-1,1),y_pred.reshape(-1,1)),axis=1))

[[0 0]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [91]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[1520   75]
 [ 200  205]]


In [92]:
print(accuracy_score(y_test,y_pred))

0.8625
